const int MAX_LIKE_COUNT = 3;

const String PERSISTENT_INDEX = 'PERSISTENT_INDEX';
const String PERSISTENT_LOOPMODE = 'PERSISTENT_LOOPMODE';
const String PERSISTENT_SHUFFLEMODE = 'PERSISTENT_SHUFFLEMODE';
const String PERSISTENT_PLAYABLE = 'PERSISTENT_PLAYABLE';

const String SETTING_ALLOWED_EXTENSIONS = 'SETTING_ALLOWED_EXTENSIONS';
const String SETTING_PLAY_ALBUMS_IN_ORDER = 'SETTING_PLAY_ALBUMS_IN_ORDER';

const String ALBUM_OF_DAY = 'ALBUM_OF_DAY';
const String ARTIST_OF_DAY = 'ARTIST_OF_DAY';

const String LISTENED_PERCENTAGE = 'LISTENED_PERCENTAGE';
