/// Flutter icons MuckeIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
import 'package:flutter/widgets.dart';

class MuckeIcons {
  MuckeIcons._();

  static const _kFontFam = 'MuckeIcons';
  static const String? _kFontPkg = null;

  static const IconData favorite_1_3 =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite_2_3 =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclude_shuffle =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclude_shuffle_all =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclude_never =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclude_always =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shuffle_heart =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
