const int MAX_LIKE_COUNT = 3;

const String PERSISTENT_INDEX = 'PERSISTENT_INDEX';
const String PERSISTENT_LOOPMODE = 'PERSISTENT_LOOPMODE';
const String PERSISTENT_SHUFFLEMODE = 'PERSISTENT_SHUFFLEMODE';
const String PERSISTENT_PLAYABLE = 'PERSISTENT_PLAYABLE';

const String SETTING_EXCLUDE_SKIPPED_SONGS = 'SETTING_EXCLUDE_SKIPPED_SONGS_ENABLED';
const String SETTING_SKIP_THRESHOLD = 'SETTING_SKIP_THRESHOLD';

const String ALBUM_OF_DAY = 'ALBUM_OF_DAY';
const String ARTIST_OF_DAY = 'ARTIST_OF_DAY';