const int MAX_LIKE_COUNT = 3;

const String PERSISTENT_INDEX = 'PERSISTENT_INDEX';
const String PERSISTENT_LOOPMODE = 'PERSISTENT_LOOPMODE';
const String PERSISTENT_SHUFFLEMODE = 'PERSISTENT_SHUFFLEMODE';
const String PERSISTENT_EXCLUDE_BLOCKED = 'PERSISTENT_EXCLUDE_BLOCKED';
const String PERSISTENT_EXCLUDE_SKIPPED = 'PERSISTENT_EXCLUDE_SKIPPED';
const String PERSISTENT_RESPECT_SONG_LINKS = 'PERSISTENT_RESPECT_SONG_LINKS';

const String SETTING_EXCLUDE_SKIPPED_SONGS = 'SETTING_EXCLUDE_SKIPPED_SONGS_ENABLED';
const String SETTING_SKIP_THRESHOLD = 'SETTING_SKIP_THRESHOLD';